- name: Delete existing content
  ansible.builtin.file:
    path: "{{ app_path }}"
    state: absent

- name: Create Application Directory
  ansible.builtin.file:
    path: "{{ app_path }}"
    state: directory
    owner: "{{app_user}}"

#- name: Downaload and extract App Content
#  ansible.builtin.unarchive:
#    src: https://expense-artifacts.s3.amazonaws.com/{{ component }}.zip
#    dest: "{{ app_path }}"
#    remote_src: yes


- name: Downaload and extract App Content from Jfrog Artifactory
  ansible.builtin.unarchive:
    src: https://{{artifactory_user}}:{{artifactory_password}}@artifactory-int.kdevops.online:8081/artifactory/expense-{{ component }}/{{app_version}}.zip
    dest: "{{ app_path }}"
    remote_src: yes
  vars:
    artifactory_user: "{{ lookup('amazon.aws.aws_ssm', 'artifactory_user', region='us-east-1' ) }}"
    artifactory_password: "{{ lookup('amazon.aws.aws_ssm', 'artifactory_password', region='us-east-1' ) }}"
    app_version: "{{ lookup('amazon.aws.aws_ssm', '{{env}}.expense.{{component}}.app_version', region='us-east-1' ) }}"
